package com.rocketmq.pojo;

import java.io.Serializable;

public class TradeUserMoneyLogKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_user_money_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_user_money_log.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_user_money_log.money_log_type
     *
     * @mbg.generated
     */
    private Integer moneyLogType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_user_money_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_money_log.user_id
     *
     * @return the value of trade_user_money_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_money_log.user_id
     *
     * @param userId the value for trade_user_money_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_money_log.order_id
     *
     * @return the value of trade_user_money_log.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_money_log.order_id
     *
     * @param orderId the value for trade_user_money_log.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_money_log.money_log_type
     *
     * @return the value of trade_user_money_log.money_log_type
     *
     * @mbg.generated
     */
    public Integer getMoneyLogType() {
        return moneyLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_money_log.money_log_type
     *
     * @param moneyLogType the value for trade_user_money_log.money_log_type
     *
     * @mbg.generated
     */
    public void setMoneyLogType(Integer moneyLogType) {
        this.moneyLogType = moneyLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", orderId=").append(orderId);
        sb.append(", moneyLogType=").append(moneyLogType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}