package com.rocketmq.pojo;

import java.io.Serializable;
import java.util.Date;

public class TradeMqConsumerLog extends TradeMqConsumerLogKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.msg_id
     *
     * @mbg.generated
     */
    private String msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.msg_body
     *
     * @mbg.generated
     */
    private String msgBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.consumer_status
     *
     * @mbg.generated
     */
    private Integer consumerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.consumer_times
     *
     * @mbg.generated
     */
    private Integer consumerTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.consumer_timestamp
     *
     * @mbg.generated
     */
    private Date consumerTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.msg_id
     *
     * @return the value of trade_mq_consumer_log.msg_id
     *
     * @mbg.generated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.msg_id
     *
     * @param msgId the value for trade_mq_consumer_log.msg_id
     *
     * @mbg.generated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.msg_body
     *
     * @return the value of trade_mq_consumer_log.msg_body
     *
     * @mbg.generated
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.msg_body
     *
     * @param msgBody the value for trade_mq_consumer_log.msg_body
     *
     * @mbg.generated
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody == null ? null : msgBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.consumer_status
     *
     * @return the value of trade_mq_consumer_log.consumer_status
     *
     * @mbg.generated
     */
    public Integer getConsumerStatus() {
        return consumerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.consumer_status
     *
     * @param consumerStatus the value for trade_mq_consumer_log.consumer_status
     *
     * @mbg.generated
     */
    public void setConsumerStatus(Integer consumerStatus) {
        this.consumerStatus = consumerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.consumer_times
     *
     * @return the value of trade_mq_consumer_log.consumer_times
     *
     * @mbg.generated
     */
    public Integer getConsumerTimes() {
        return consumerTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.consumer_times
     *
     * @param consumerTimes the value for trade_mq_consumer_log.consumer_times
     *
     * @mbg.generated
     */
    public void setConsumerTimes(Integer consumerTimes) {
        this.consumerTimes = consumerTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.consumer_timestamp
     *
     * @return the value of trade_mq_consumer_log.consumer_timestamp
     *
     * @mbg.generated
     */
    public Date getConsumerTimestamp() {
        return consumerTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.consumer_timestamp
     *
     * @param consumerTimestamp the value for trade_mq_consumer_log.consumer_timestamp
     *
     * @mbg.generated
     */
    public void setConsumerTimestamp(Date consumerTimestamp) {
        this.consumerTimestamp = consumerTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.remark
     *
     * @return the value of trade_mq_consumer_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.remark
     *
     * @param remark the value for trade_mq_consumer_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgId=").append(msgId);
        sb.append(", msgBody=").append(msgBody);
        sb.append(", consumerStatus=").append(consumerStatus);
        sb.append(", consumerTimes=").append(consumerTimes);
        sb.append(", consumerTimestamp=").append(consumerTimestamp);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}