package com.rocketmq.mapper;

import com.rocketmq.pojo.TradeMqProducerTemp;
import com.rocketmq.pojo.TradeMqProducerTempExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMqProducerTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    long countByExample(TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int deleteByExample(TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int insert(TradeMqProducerTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int insertSelective(TradeMqProducerTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    List<TradeMqProducerTemp> selectByExample(TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    TradeMqProducerTemp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeMqProducerTemp record, @Param("example") TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeMqProducerTemp record, @Param("example") TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeMqProducerTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeMqProducerTemp record);
}