package com.rocketmq.mapper;

import com.rocketmq.pojo.TradeCoupon;
import com.rocketmq.pojo.TradeCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    long countByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int insert(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int insertSelective(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    List<TradeCoupon> selectByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    TradeCoupon selectByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeCoupon record, @Param("example") TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeCoupon record, @Param("example") TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeCoupon record);
}