package com.rocketmq.mapper;

import com.rocketmq.pojo.TradePay;
import com.rocketmq.pojo.TradePayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradePayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    long countByExample(TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int deleteByExample(TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int insert(TradePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int insertSelective(TradePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    List<TradePay> selectByExample(TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    TradePay selectByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradePay record, @Param("example") TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradePay record, @Param("example") TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradePay record);
}