package com.rocketmq.mapper;

import com.rocketmq.pojo.TradeGoods;
import com.rocketmq.pojo.TradeGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    long countByExample(TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int deleteByExample(TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int insert(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int insertSelective(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    List<TradeGoods> selectByExample(TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    TradeGoods selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeGoods record, @Param("example") TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeGoods record, @Param("example") TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeGoods record);
}