package com.rocketmq.mapper;

import com.rocketmq.pojo.TradeGoodsNumberLog;
import com.rocketmq.pojo.TradeGoodsNumberLogExample;
import com.rocketmq.pojo.TradeGoodsNumberLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeGoodsNumberLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    long countByExample(TradeGoodsNumberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int deleteByExample(TradeGoodsNumberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TradeGoodsNumberLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int insert(TradeGoodsNumberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int insertSelective(TradeGoodsNumberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    List<TradeGoodsNumberLog> selectByExample(TradeGoodsNumberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    TradeGoodsNumberLog selectByPrimaryKey(TradeGoodsNumberLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeGoodsNumberLog record, @Param("example") TradeGoodsNumberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeGoodsNumberLog record, @Param("example") TradeGoodsNumberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeGoodsNumberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeGoodsNumberLog record);
}