package com.rocketmq.mapper;

import com.rocketmq.pojo.TradeMqConsumerLog;
import com.rocketmq.pojo.TradeMqConsumerLogExample;
import com.rocketmq.pojo.TradeMqConsumerLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMqConsumerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    long countByExample(TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int deleteByExample(TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TradeMqConsumerLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int insert(TradeMqConsumerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int insertSelective(TradeMqConsumerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    List<TradeMqConsumerLog> selectByExample(TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    TradeMqConsumerLog selectByPrimaryKey(TradeMqConsumerLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeMqConsumerLog record, @Param("example") TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeMqConsumerLog record, @Param("example") TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeMqConsumerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeMqConsumerLog record);
}