package com.rocketmq.mapper;

import com.rocketmq.pojo.TradeOrder;
import com.rocketmq.pojo.TradeOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    long countByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int deleteByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int insert(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int insertSelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    List<TradeOrder> selectByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    TradeOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeOrder record);
}