# 基本服务配置
server:
  port: 10003 # 端口
spring:
  application:
    name: shop-goods-service # 服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 连接数据库方式
    url: jdbc:mysql://localhost:3306/trade?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useUnicode=false # 连接数据库基本信息
    username: root # 连接数据库用户名
    password: A18716296148 # 连接数据库密码
    type: com.alibaba.druid.pool.DruidDataSource # 数据库连接池
# mybatis 配置
mybatis:
  type-aliases-package: com.rocketmq.pojo # 自动起别名
  mapper-locations: classpath*:/mapper/*.xml # 如果mapper的xml文件保存到的是resources下mapper下
  configuration:
    map-underscore-to-camel-case: true # 驼峰名适配
# dubbo 配置
dubbo:
  application:
    name: shop-goods-service # dubbo 名称
    qos-enable: true
    qos-port: 33335
    logger: slf4j # # 日志输出方式，可选：slf4j jcl log4j jdk
  registry:
    address: zookeeper://192.168.1.125:2181?backup=192.168.1.126:2181,192.168.1.127:2181 # 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔（必填）
    port: 2181 # 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值（9090）
    protocol: zookeeper # 注册中心地址协议，支持dubbo  http  local三种协议（dubbo）
    client: curator # Zookeeper客户端，可选：zkclient  curator
    check: true # 注册中心不存在时，是否报错
    transporter: netty # 网络传输方式，可选mina netty
    timeout: 100000 # 注册中心请求超时时间(毫秒)
  protocol:
    name: dubbo
    port: 20883
    status: server
    threadpool: cached # 线程池类型，可选：fixed  cached
    threads: 100 # 服务线程池大小(固定大小)
    accesslog: true # 设为true，将向logger中输出访问日志，也可填写访问日志文件路径，直接把访问日志输出到指定文件
  config-center:
    address: zookeeper://192.168.1.125:2181?backup=192.168.1.126:2181,192.168.1.127:2181
    timeout: 10000
  metadata-report:
    address: zookeeper://192.168.1.125:2181?backup=192.168.1.126:2181,192.168.1.127:2181
    timeout: 10000
  scan:
    base-packages: com.rocketmq.service
# rocketmq 配置
rocketmq:
  name-server: 192.168.1.125:9876;192.168.1.126:9876 # NameServer
  producer:
    group: orderProducerGroup
    retry-times-when-send-failed: 5 # 因时间过时而发送失败消息的重试次数
    retry-times-when-send-async-failed: 2 # 异步消息发送失败重试次数
    max-message-size: 4194304 # 设置一条消息的最大大小，4MB
    send-message-timeout: 3000 # 设置消息发送过期时间
    compress-message-body-threshold: 4096 # 消息大小超过 4k，则被压缩，默认大小4k
    retry-next-server: false # 消息存储失败，是否允许发送换 broker
# slf4j 日志配置
logging:
  file:
    path: E:/logs/rocketmq-parent/shop-goods-service.log





